name: CI-CodeBuild 🚀

on:
  workflow_dispatch:

jobs:
  job1:
  
    runs-on:
      - codebuild-gh-dylagray-approval-worklfows-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
      - deployment-status-override:true
    environment: prod
    steps:
      - name: test command
        run: echo "HELLO WORLD"
